M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sun 05 Feb 2023 03:08:22 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-05T15:08:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.1Y-3.6
T2
X2.85Y-4.15
X3.15Y-4.15
X3.65Y-4.15
X3.95Y-4.15
X4.4Y-4.15
X4.7Y-4.15
T0
M30
