M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sun 15 Jan 2023 02:43:10 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-15T14:43:10-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.1701Y-4.6012
X4.1701Y-4.8288
T2
X3.125Y-5.8
X3.575Y-5.8
T0
M30
