M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Wed 16 Nov 2022 09:07:18 AM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-16T09:07:18-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0512
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X2.575Y-3.2099
X2.575Y-3.3477
T4
X2.2Y-2.3
X2.2Y-3.4
X3.8Y-2.3
X3.8Y-3.4
T2
G00X3.05Y-3.1933
M15
G01X3.05Y-3.2524
M16
G05
T3
G00X3.0736Y-3.4
M15
G01X3.0264Y-3.4
M16
G05
T0
M30
